"""Build Chapter 11 notebook: MLOps and Deployment."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from _nbutils import build_notebook, md, code

CHAPTER = 11
OUT = pathlib.Path(__file__).parent / f"Chapter_{CHAPTER:02d}" / f"Chapter_{CHAPTER:02d}_MLOps_and_Deployment.ipynb"

cells = []
cells.append(md(
    "# Chapter 11: MLOps and Deployment\n"
    "\n"
    "*Deep Learning Crash Course - BPB Publications*\n"
    "\n"
    "This chapter is about turning a trained model into a reliable production service. The "
    "notebook walks through model packaging (SavedModel, TorchScript, ONNX), a FastAPI "
    "inference server, a model-card template, a multi-stage Dockerfile, MLflow tracking, "
    "a GitHub Actions CI workflow and safe deployment strategies. Each section saves "
    "concrete artefacts you can ship.\n"
))

cells.append(md("## 1. Setup"))
cells.append(code(
    "import os, json, time, random, hashlib\n"
    "from pathlib import Path\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "IMG_DIR = Path('images'); IMG_DIR.mkdir(exist_ok=True)\n"
    "ARTIFACTS = Path('artifacts'); ARTIFACTS.mkdir(exist_ok=True)\n"
    "def set_seed(s=42):\n"
    "    os.environ['PYTHONHASHSEED']=str(s); random.seed(s); np.random.seed(s)\n"
    "    try:\n"
    "        import torch; torch.manual_seed(s); torch.cuda.manual_seed_all(s)\n"
    "    except ModuleNotFoundError: pass\n"
    "set_seed(42)\n"
))

cells.append(md("## 2. Train and package a small reference model\n"
                "\n"
                "We train a tiny MLP on MNIST and export it to three production formats:\n"
                "1. PyTorch state-dict (the original) — useful for retraining and PyTorch-native serving.\n"
                "2. TorchScript — frozen graph for `torch.jit.load`.\n"
                "3. ONNX — runtime-neutral; works with ONNX Runtime, TensorRT, OpenVINO."))
cells.append(code(
    "import torch\n"
    "import torch.nn as nn\n"
    "from torchvision import datasets, transforms\n"
    "from torch.utils.data import DataLoader\n"
    "\n"
    "tf = transforms.Compose([transforms.ToTensor(), transforms.Lambda(lambda x: x.view(-1))])\n"
    "train = DataLoader(datasets.MNIST('./data', train=True, download=True, transform=tf), batch_size=128, shuffle=True)\n"
    "test  = DataLoader(datasets.MNIST('./data', train=False, download=True, transform=tf), batch_size=512)\n"
    "\n"
    "class MLP(nn.Module):\n"
    "    def __init__(self):\n"
    "        super().__init__()\n"
    "        self.net = nn.Sequential(nn.Linear(784, 128), nn.ReLU(), nn.Linear(128, 10))\n"
    "    def forward(self, x): return self.net(x)\n"
    "\n"
    "model = MLP(); opt = torch.optim.Adam(model.parameters(), lr=1e-3); loss_fn = nn.CrossEntropyLoss()\n"
    "for ep in range(1):\n"
    "    model.train()\n"
    "    for xb, yb in train: opt.zero_grad(); loss_fn(model(xb), yb).backward(); opt.step()\n"
    "model.eval()\n"
    "correct = sum((model(xb).argmax(1) == yb).sum().item() for xb, yb in test)\n"
    "acc = correct / len(test.dataset)\n"
    "print(f'Accuracy: {acc:.4f}')\n"
    "\n"
    "torch.save(model.state_dict(), ARTIFACTS / 'model.pt')\n"
    "scripted = torch.jit.script(model); torch.jit.save(scripted, ARTIFACTS / 'model.ts')\n"
    "dummy = torch.zeros(1, 784)\n"
    "# dynamo=False uses the legacy tracing exporter, which has no extra deps.\n"
    "# Set dynamo=True (the new default in PyTorch >=2.5) once `onnxscript` is\n"
    "# installed; the dynamo path produces a more accurate, fully-fused graph.\n"
    "torch.onnx.export(model, dummy, str(ARTIFACTS / 'model.onnx'),\n"
    "                  input_names=['x'], output_names=['logits'],\n"
    "                  dynamic_axes={'x': {0: 'batch'}, 'logits': {0: 'batch'}},\n"
    "                  opset_version=17, dynamo=False)\n"
    "for f in ARTIFACTS.iterdir():\n"
    "    print(f'{f.name:14s} {f.stat().st_size/1e3:7.1f} kB')\n"
))

cells.append(md("## 3. Write a Model Card\n"
                "\n"
                "A model card is the deployment passport - it travels with the model artefact so "
                "downstream users (or auditors) know what they are running."))
cells.append(code(
    "MODEL_CARD = {\n"
    "    'model_details': {\n"
    "        'name': 'mnist-mlp', 'version': '0.1.0',\n"
    "        'authors': ['Samaresh K. Singh', 'Joyjit Roy'],\n"
    "        'framework': 'PyTorch 2.x',\n"
    "        'training_dataset': 'MNIST 60k',\n"
    "    },\n"
    "    'intended_use': {\n"
    "        'primary': 'Educational - classify handwritten digits 0-9.',\n"
    "        'out_of_scope': ['real-world handwriting recognition', 'multi-language scripts'],\n"
    "    },\n"
    "    'evaluation': {\n"
    "        'metric': 'test accuracy',\n"
    "        'value': round(acc, 4),\n"
    "        'dataset': 'MNIST 10k test',\n"
    "    },\n"
    "    'ethical_considerations': [\n"
    "        'No demographic information used.',\n"
    "        'Not validated on non-Latin numerals.',\n"
    "    ],\n"
    "    'limitations': ['Sensitive to background noise outside MNIST distribution.'],\n"
    "    'hash': hashlib.sha256((ARTIFACTS / 'model.pt').read_bytes()).hexdigest()[:16],\n"
    "    'timestamp': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),\n"
    "}\n"
    "(ARTIFACTS / 'model_card.json').write_text(json.dumps(MODEL_CARD, indent=2))\n"
    "print(json.dumps(MODEL_CARD, indent=2))\n"
))

cells.append(md("## 4. FastAPI inference server (sketch)\n"
                "\n"
                "We write the server module to `artifacts/server.py`. Launch with `uvicorn artifacts.server:app`. "
                "The lifespan context loads the model once at startup - the chapter's recommended pattern."))
cells.append(code(
    "SERVER = '''\n"
    "from contextlib import asynccontextmanager\n"
    "from pathlib import Path\n"
    "from fastapi import FastAPI, HTTPException\n"
    "from pydantic import BaseModel, Field\n"
    "import torch\n"
    "import time\n"
    "\n"
    "MODEL = {}\n"
    "\n"
    "class PredictIn(BaseModel):\n"
    "    pixels: list[float] = Field(..., min_length=784, max_length=784)\n"
    "\n"
    "class PredictOut(BaseModel):\n"
    "    digit: int\n"
    "    probabilities: list[float]\n"
    "    latency_ms: float\n"
    "\n"
    "@asynccontextmanager\n"
    "async def lifespan(app: FastAPI):\n"
    "    state_dict = torch.load(Path(__file__).parent / 'model.pt', map_location='cpu')\n"
    "    net = torch.nn.Sequential(torch.nn.Linear(784, 128), torch.nn.ReLU(), torch.nn.Linear(128, 10))\n"
    "    net.load_state_dict({k.replace('net.', ''): v for k, v in state_dict.items()})\n"
    "    net.eval()\n"
    "    MODEL['net'] = net\n"
    "    yield\n"
    "    MODEL.clear()\n"
    "\n"
    "app = FastAPI(lifespan=lifespan, title='MNIST MLP inference')\n"
    "\n"
    "@app.get('/health')\n"
    "def health(): return {'status': 'ok'}\n"
    "\n"
    "@app.post('/v1/predict', response_model=PredictOut)\n"
    "def predict(req: PredictIn):\n"
    "    t0 = time.perf_counter()\n"
    "    if 'net' not in MODEL:\n"
    "        raise HTTPException(503, 'Model not loaded')\n"
    "    x = torch.tensor([req.pixels], dtype=torch.float32)\n"
    "    with torch.no_grad():\n"
    "        logits = MODEL['net'](x)\n"
    "        probs = torch.softmax(logits, dim=1)[0]\n"
    "    return PredictOut(digit=int(probs.argmax().item()),\n"
    "                      probabilities=probs.tolist(),\n"
    "                      latency_ms=(time.perf_counter() - t0) * 1000)\n"
    "'''\n"
    "server_path = ARTIFACTS / 'server.py'\n"
    "server_path.write_text(SERVER)\n"
    "print(f'Wrote {server_path} ({len(SERVER)} bytes)')\n"
))

cells.append(md("## 5. Production Dockerfile (multi-stage)\n"
                "\n"
                "The first stage installs build dependencies and the model. The second stage copies "
                "only the runtime needed to serve, producing a slim image."))
cells.append(code(
    "DOCKERFILE = '''\n"
    "# syntax=docker/dockerfile:1\n"
    "FROM python:3.11-slim AS builder\n"
    "WORKDIR /build\n"
    "RUN pip install --no-cache-dir torch==2.3.0 fastapi==0.111.0 uvicorn==0.30.0 pydantic==2.7.1\n"
    "COPY artifacts/model.pt /build/model.pt\n"
    "\n"
    "FROM python:3.11-slim AS runtime\n"
    "WORKDIR /app\n"
    "COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages\n"
    "COPY --from=builder /usr/local/bin/uvicorn /usr/local/bin/uvicorn\n"
    "COPY --from=builder /build/model.pt /app/model.pt\n"
    "COPY artifacts/server.py /app/server.py\n"
    "ENV PYTHONUNBUFFERED=1\n"
    "EXPOSE 8000\n"
    "HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\\\\n"
    "  CMD python -c \"import urllib.request, sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/health').status==200 else 1)\"\n"
    "CMD [\"uvicorn\", \"server:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\", \"--workers\", \"1\"]\n"
    "'''\n"
    "(ARTIFACTS / 'Dockerfile').write_text(DOCKERFILE)\n"
    "print(DOCKERFILE.strip())\n"
))

cells.append(md("## 6. MLflow tracking and a model registry sketch\n"
                "\n"
                "MLflow is the de facto standard for experiment tracking and a lightweight model "
                "registry. The cell below uses an in-process local filestore so it runs without "
                "any infrastructure."))
cells.append(code(
    "try:\n"
    "    import mlflow, mlflow.pytorch\n"
    "    mlflow.set_tracking_uri('file://' + str(Path('mlruns').absolute()))\n"
    "    mlflow.set_experiment('mnist-mlp')\n"
    "    with mlflow.start_run(run_name='v0.1.0') as run:\n"
    "        mlflow.log_params({'lr': 1e-3, 'batch_size': 128, 'epochs': 1})\n"
    "        mlflow.log_metrics({'test_accuracy': float(acc)})\n"
    "        mlflow.log_artifact(str(ARTIFACTS / 'model_card.json'))\n"
    "        mlflow.pytorch.log_model(model, artifact_path='model')\n"
    "    print('Logged MLflow run', run.info.run_id)\n"
    "except ModuleNotFoundError:\n"
    "    print('MLflow not installed - skipping. (pip install mlflow)')\n"
))

cells.append(md("## 7. GitHub Actions CI workflow with a quality gate"))
cells.append(code(
    "GH_WORKFLOW = '''\n"
    "name: CI\n"
    "on:\n"
    "  pull_request:\n"
    "  push: { branches: [main] }\n"
    "jobs:\n"
    "  test:\n"
    "    runs-on: ubuntu-latest\n"
    "    env: { MIN_ACCURACY: '0.88' }\n"
    "    steps:\n"
    "      - uses: actions/checkout@v4\n"
    "      - uses: actions/setup-python@v5\n"
    "        with: { python-version: '3.11' }\n"
    "      - run: pip install -r requirements.txt\n"
    "      - name: Run training smoke test\n"
    "        run: python -m pytest tests/test_train_smoke.py -q\n"
    "      - name: Evaluate against quality gate\n"
    "        run: |\n"
    "          ACC=$(python scripts/evaluate.py --model artifacts/model.pt)\n"
    "          python -c \"import sys; sys.exit(0 if float('$ACC') >= float('$MIN_ACCURACY') else 1)\"\n"
    "      - name: Build container\n"
    "        if: success()\n"
    "        run: docker build -t mnist-mlp:${{ github.sha }} .\n"
    "'''\n"
    "(ARTIFACTS / 'github_ci.yml').write_text(GH_WORKFLOW)\n"
    "print(GH_WORKFLOW.strip())\n"
))

cells.append(md("## 8. Safe deployment strategies\n"
                "\n"
                "Visualise the three roll-out patterns described in the chapter: blue-green, canary "
                "and shadow."))
cells.append(code(
    "fig, axes = plt.subplots(1, 3, figsize=(12, 3.5))\n"
    "for ax, (name, share) in zip(axes,\n"
    "        [('Blue-Green',  [(0, 'blue', 'v1'), (1, 'green', 'v2')]),\n"
    "         ('Canary 10%',  [(0.9, 'gray', 'v1 - 90%'), (0.1, 'orange', 'v2 - 10%')]),\n"
    "         ('Shadow mode', [(1.0, 'gray', 'v1 (live)'), (0.0, 'orange', 'v2 (logged only)')])]):\n"
    "    cum = 0\n"
    "    for frac, color, label in share:\n"
    "        ax.barh(0, frac, left=cum, color=color, edgecolor='black')\n"
    "        ax.text(cum + max(frac, 0.02)/2, 0, label, ha='center', va='center', color='white', fontsize=9)\n"
    "        cum += frac\n"
    "    ax.set_xlim(0, 1); ax.set_yticks([]); ax.set_title(name); ax.set_xlabel('traffic share')\n"
    "fig.suptitle('Deployment strategies')\n"
    "fig.tight_layout(); fig.savefig(IMG_DIR / '01_deployment_strategies.png', dpi=150); plt.show()\n"
))

cells.append(md("## 9. Exercise solutions\n"
                "\n"
                "### 9.1 MCQ answer key\n"
                "\n"
                "| Q | Answer | Why |\n"
                "|---|--------|-----|\n"
                "| 1 | (c) ONNX | The portable cross-runtime format. |\n"
                "| 2 | (b) Cold-start latency | Loading at request time blocks the first request for seconds. |\n"
                "| 3 | (b) Build cache reuse | Model layer rarely changes; app.py changes often. |\n"
                "| 4 | (b) Pre/post-processing logic | Translates raw input into tensors and back. |\n"
                "| 5 | (b) Archives the prior production version | Atomic switchover with rollback. |\n"
                "| 6 | (c) Trained model's accuracy < 0.88 | Quality gate. |\n"
                "| 7 | (b) Sends a copy of traffic, no response | Tests new model offline. |\n"
                "| 8 | (b) Adjusts instance count to target invocations/instance | Standard SageMaker autoscaling. |\n"
                "| 9 | (b) Structured ethics, limitations, evaluation | Beyond install/usage docs. |\n"
                "| 10 | (b) Batchable requests with low p99 SLA | Throughput-bound inference. |\n"
                "| 11 | (b) 10% of requests go to the new version | Standard canary. |\n"
                "| 12 | (b) TorchServe handles batching, metrics and multi-model | Production server features. |\n"))

cells.append(md("### 9.2 TensorFlow image classifier -> Android 4 MB, 20 ms\n"
                "1. **Export** `SavedModel` -> **TFLite** with `tf.lite.TFLiteConverter.from_saved_model(...)`.\n"
                "2. **Quantize** with INT8 post-training (representative dataset of ~100 calibration images).\n"
                "3. **Verify** accuracy with a TFLite `Interpreter` against the FP32 validation set; aim for <1 pp drop.\n"
                "4. **Profile** on the actual device with TensorFlow Lite Benchmark Tool. If 20 ms is missed, enable the **GPU or NNAPI delegate**.\n"
                "5. **Ship** the .tflite (typically 1-3 MB after INT8) plus a JSON label map.\n"))

cells.append(md("### 9.3 FastAPI 300 RPS at p99 180 ms\n"
                "Model inference is 15 ms but p99 latency is 180 ms - so 165 ms is non-model overhead.\n"
                "1. **Uvicorn workers**: increase `--workers` to `num_cpu_cores`; default 1 is the most common cause of queueing. Verify by checking that the latency curve flattens after the change.\n"
                "2. **Pydantic validation**: switch to `Pydantic V2`, mark request/response models with `model_config = ConfigDict(arbitrary_types_allowed=True, defer_build=True)` and avoid validators that do expensive coercion.\n"
                "3. **ONNX Runtime session**: load with `InferenceSession(..., providers=['CPUExecutionProvider'], sess_options=so)` where `so.intra_op_num_threads = 1` and `so.execution_mode = ORT_PARALLEL` to keep per-request threading deterministic. Pre-allocate I/O buffers to skip the per-request allocation."))

cells.append(md("### 9.4 91% in January, 79% in June\n"
                "Diagnostic checklist:\n"
                "1. **Compare current input feature distribution to training**: KS test on each numeric feature, PSI on each categorical. PSI > 0.2 is the standard alarm threshold.\n"
                "2. **Inspect ground-truth label distribution**: was the operational definition of the label changed?\n"
                "3. **Check prediction-distribution drift**: are predicted class proportions the same as in January? Sudden shifts hint at upstream pipeline bugs (e.g. timezone, missing feature column).\n"
                "4. **Backfill a few weeks of feature drift telemetry** and look for the change point.\n"
                "5. **Remediation menu**: (a) hot-fix the broken feature; (b) retrain with the most recent 90 days; (c) deploy a shadow model and compare A/B before promoting; (d) reset to a previous model version while the drift is investigated."))

cells.append(md("### 9.5 MLflow schema for three different-framework models\n"
                "**Experiments**: one per *model family* (`vision`, `nlp`, `tabular`).\n"
                "**Runs**: tagged with `framework=tf|pytorch|sklearn`, `model_version`, `git_commit`, `training_data_uri`.\n"
                "**Metrics**: a normalised set so different frameworks are comparable: `accuracy`, `latency_p50_ms`, `latency_p99_ms`, `inference_throughput`.\n"
                "**Quality gates**: implemented as an MLflow `Registered Model -> Staging -> Production` transition that requires (a) accuracy ≥ baseline, (b) latency within budget, (c) model card present, (d) signed off by 2 reviewers (Slack/Github integration).\n"
                "**Audit trail**: every transition is logged with `mlflow.transition_model_version_stage(..., archive_existing_versions=True)` and the previous Production version is archived rather than deleted."))

cells.append(md("### 9.6 Blue-green vs canary for fraud detection (£200 vs £5)\n"
                "False-negative cost (£200) is 40x false-positive cost (£5), so a missed fraud is much more expensive than a blocked legitimate transaction. **Canary** is the safer roll-out because it limits the blast radius of a model with a higher false-negative rate to ~10 percent of traffic.\n"
                "Monitoring thresholds for the canary decision:\n"
                "- **TPR (recall) on confirmed fraud**: must be within 1 pp of the previous model.\n"
                "- **FPR on legitimate traffic**: must be within 0.05 pp of the previous model.\n"
                "- **Expected loss per 1k transactions** (using the cost structure above): the new model's loss must be at least 5 percent lower than the previous model's loss.\n"
                "Decision: promote when all three metrics are within thresholds over a 24 hour window, otherwise rollback within 10 minutes."))

cells.append(md("### 9.7 PPO agent for robot arm in a factory\n"
                "**Packaging**: TorchScript - deterministic, frozen graph, no Python dependency on the controller.\n"
                "**API**: `POST /v1/act` returning `{action, value, action_logprob, model_version}` and `POST /v1/act/batch` for batch inference.\n"
                "**Safety**:\n"
                "- **Action clipping**: bounds enforced on the controller side, never trust the model output.\n"
                "- **Confidence threshold**: if `entropy(policy) > entropy_max`, fall back to a safe pre-programmed action.\n"
                "- **Sim-to-real shadow mode**: run the policy in simulation in parallel with the real action and alert on large divergence.\n"
                "**Monitoring**: action distribution PSI vs training, episode return, policy value estimate vs realised reward, mean episode length.\n"
                "**Rollback trigger**: confidence threshold breach for > 5 consecutive episodes, OR a single safety-system halt event."))

cells.append(md("### 9.8 14-day Jupyter -> AWS production plan\n"
                "**Phase 1 (days 1-3, fastest path to serving)**: Export model -> SageMaker single-instance endpoint (`pytorch-inference` image) -> FastAPI wrapper for I/O contract. Success criterion: production endpoint returns predictions for 10 sample requests.\n"
                "**Phase 2 (days 4-10, production hardening)**: Add autoscaling (target invocations/instance), CloudWatch alarms (latency, 5xx rate), structured logging, MLflow model registry, IAM least-privilege role for the endpoint. Success criterion: load test at 2x expected peak passes with p99 within SLA.\n"
                "**Phase 3 (days 11-14, operational excellence)**: Drift monitoring (Evidently AI nightly job), CI/CD via GitHub Actions, canary deployment pipeline with manual approval gate, runbook + alert escalation rota. Success criterion: a deliberate degraded model deployment is rolled back automatically within 10 minutes by the canary gate."))

cells.append(md("---\n*End of Chapter 11. Generated artefacts live in `artifacts/`.*\n"))

build_notebook(cells, OUT, kernel_name='python3', display_name='Python 3 (Deep Learning)')
print('Built', OUT)
