"""Build Chapter 9 notebook: Model Optimization and Compression."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from _nbutils import build_notebook, md, code

CHAPTER = 9
OUT = pathlib.Path(__file__).parent / f"Chapter_{CHAPTER:02d}" / f"Chapter_{CHAPTER:02d}_Model_Optimization.ipynb"

cells = []
cells.append(md(
    "# Chapter 9: Model Optimization and Compression\n"
    "\n"
    "*Deep Learning Crash Course - BPB Publications*\n"
    "\n"
    "We compress a small CNN with magnitude pruning, post-training INT8 quantization, "
    "quantization-aware training and knowledge distillation. Each section measures the "
    "**three deployment quantities** that matter: model size on disk, inference latency "
    "and accuracy.\n"
))

cells.append(md("## 1. Setup and a small reference model"))
cells.append(code(
    "import os, time, copy, random\n"
    "from pathlib import Path\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "IMG_DIR = Path('images'); IMG_DIR.mkdir(exist_ok=True)\n"
    "def set_seed(s=42):\n"
    "    os.environ['PYTHONHASHSEED']=str(s); random.seed(s); np.random.seed(s)\n"
    "    try:\n"
    "        import torch; torch.manual_seed(s); torch.cuda.manual_seed_all(s)\n"
    "    except ModuleNotFoundError: pass\n"
    "set_seed(42)\n"
))
cells.append(code(
    "import torch\n"
    "import torch.nn as nn\n"
    "from torchvision import datasets, transforms\n"
    "from torch.utils.data import DataLoader\n"
    "device = 'cpu'  # most compression APIs are CPU-only in PyTorch\n"
    "\n"
    "tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])\n"
    "train = DataLoader(datasets.MNIST('./data', train=True, download=True, transform=tf), batch_size=128, shuffle=True)\n"
    "test  = DataLoader(datasets.MNIST('./data', train=False, download=True, transform=tf), batch_size=512)\n"
    "\n"
    "class SmallCNN(nn.Module):\n"
    "    # QuantStub / DeQuantStub mark the float<->quantized boundaries used by\n"
    "    # PyTorch's quantization-aware training pipeline. They are no-ops in float\n"
    "    # mode, so the same class is used by both the baseline and the QAT examples.\n"
    "    def __init__(self):\n"
    "        super().__init__()\n"
    "        self.quant = torch.quantization.QuantStub()\n"
    "        self.dequant = torch.quantization.DeQuantStub()\n"
    "        self.features = nn.Sequential(\n"
    "            nn.Conv2d(1, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n"
    "            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n"
    "        )\n"
    "        self.classifier = nn.Sequential(\n"
    "            nn.Flatten(), nn.Linear(64 * 7 * 7, 128), nn.ReLU(),\n"
    "            nn.Linear(128, 10))\n"
    "    def forward(self, x):\n"
    "        x = self.quant(x)\n"
    "        x = self.classifier(self.features(x))\n"
    "        return self.dequant(x)\n"
    "\n"
    "def train_model(model, epochs=1, lr=1e-3):\n"
    "    opt = torch.optim.Adam(model.parameters(), lr=lr)\n"
    "    loss_fn = nn.CrossEntropyLoss()\n"
    "    for ep in range(epochs):\n"
    "        model.train()\n"
    "        for xb, yb in train:\n"
    "            opt.zero_grad(); loss = loss_fn(model(xb), yb); loss.backward(); opt.step()\n"
    "    return model\n"
    "\n"
    "def evaluate(model, loader=test):\n"
    "    model.eval(); correct = 0; total = 0\n"
    "    with torch.no_grad():\n"
    "        for xb, yb in loader:\n"
    "            correct += (model(xb).argmax(1) == yb).sum().item(); total += yb.size(0)\n"
    "    return correct / total\n"
    "\n"
    "def model_size_mb(model, path='./tmp.pt'):\n"
    "    torch.save(model.state_dict(), path)\n"
    "    size = os.path.getsize(path) / 1e6\n"
    "    os.remove(path)\n"
    "    return size\n"
    "\n"
    "def latency(model, n=200):\n"
    "    model.eval()\n"
    "    x = torch.randn(1, 1, 28, 28)\n"
    "    with torch.no_grad():\n"
    "        for _ in range(10): model(x)\n"
    "        t0 = time.perf_counter()\n"
    "        for _ in range(n): model(x)\n"
    "        return (time.perf_counter() - t0) / n * 1e3  # ms\n"
    "\n"
    "baseline = SmallCNN()\n"
    "train_model(baseline, epochs=1)\n"
    "print(f'Baseline | accuracy {evaluate(baseline):.4f} | size {model_size_mb(baseline):.2f} MB | latency {latency(baseline):.2f} ms')\n"
))

cells.append(md("## 2. Magnitude pruning\n"
                "\n"
                "Remove the smallest-magnitude weights from each layer. PyTorch's `torch.nn.utils.prune` "
                "stores the pruning mask alongside the original weights."))
cells.append(code(
    "import torch.nn.utils.prune as prune\n"
    "\n"
    "def prune_global(model, amount=0.5):\n"
    "    params = [(m, 'weight') for m in model.modules() if isinstance(m, (nn.Linear, nn.Conv2d))]\n"
    "    prune.global_unstructured(params, pruning_method=prune.L1Unstructured, amount=amount)\n"
    "    for module, _ in params:\n"
    "        prune.remove(module, 'weight')  # bake mask into weights\n"
    "    return model\n"
    "\n"
    "def sparsity(model):\n"
    "    total = zeros = 0\n"
    "    for m in model.modules():\n"
    "        if isinstance(m, (nn.Linear, nn.Conv2d)):\n"
    "            total += m.weight.numel(); zeros += (m.weight == 0).sum().item()\n"
    "    return zeros / total\n"
    "\n"
    "pruned = prune_global(copy.deepcopy(baseline), amount=0.5)\n"
    "print(f'After 50% prune: sparsity {sparsity(pruned):.2f} | accuracy {evaluate(pruned):.4f}')\n"
    "# A quick fine-tune to recover any accuracy lost\n"
    "train_model(pruned, epochs=1, lr=1e-4)\n"
    "print(f'After 1 epoch fine-tune: accuracy {evaluate(pruned):.4f}')\n"
))

cells.append(md("## 3. Post-training dynamic quantization (INT8)\n"
                "\n"
                "Dynamic quantization replaces `nn.Linear` weights with int8 at load time. Activations "
                "stay in float32. This is the cheapest form of quantization and works well for "
                "MLP- and Transformer-style models."))
cells.append(code(
    "quant_dynamic = torch.quantization.quantize_dynamic(\n"
    "    copy.deepcopy(baseline), {nn.Linear}, dtype=torch.qint8)\n"
    "print(f'Dynamic INT8 | accuracy {evaluate(quant_dynamic):.4f} | size {model_size_mb(quant_dynamic):.2f} MB | latency {latency(quant_dynamic):.2f} ms')\n"
))

cells.append(md("## 4. Quantization-aware training (QAT)\n"
                "\n"
                "QAT inserts fake-quant nodes during training so the model learns weights that "
                "still work after rounding. It recovers most of the accuracy lost in post-training "
                "quantization on hard-to-quantize layers."))
cells.append(code(
    "qat = SmallCNN()\n"
    "qat.qconfig = torch.quantization.get_default_qat_qconfig('x86')\n"
    "qat = torch.quantization.prepare_qat(qat.train())\n"
    "train_model(qat, epochs=1)\n"
    "qat.eval(); qat_quant = torch.quantization.convert(qat)\n"
    "print(f'QAT INT8 | accuracy {evaluate(qat_quant):.4f} | size {model_size_mb(qat_quant):.2f} MB')\n"
))

cells.append(md("## 5. Knowledge distillation\n"
                "\n"
                "A small *student* network learns to match the *teacher's* soft labels - a Kullback-Leibler "
                "divergence between teacher and student softmax outputs at temperature $T$."))
cells.append(code(
    "import torch.nn.functional as F\n"
    "\n"
    "class TinyStudent(nn.Module):\n"
    "    def __init__(self):\n"
    "        super().__init__()\n"
    "        self.net = nn.Sequential(\n"
    "            nn.Flatten(), nn.Linear(28 * 28, 64), nn.ReLU(), nn.Linear(64, 10))\n"
    "    def forward(self, x): return self.net(x)\n"
    "\n"
    "def distill_loss(student_logits, teacher_logits, labels, T=4.0, alpha=0.7):\n"
    "    soft = F.kl_div(F.log_softmax(student_logits / T, dim=1),\n"
    "                    F.softmax(teacher_logits / T, dim=1), reduction='batchmean') * (T * T)\n"
    "    hard = F.cross_entropy(student_logits, labels)\n"
    "    return alpha * soft + (1 - alpha) * hard\n"
    "\n"
    "teacher = baseline.eval()\n"
    "student = TinyStudent()\n"
    "opt = torch.optim.Adam(student.parameters(), lr=1e-3)\n"
    "for ep in range(1):\n"
    "    student.train()\n"
    "    for xb, yb in train:\n"
    "        with torch.no_grad(): logits_t = teacher(xb)\n"
    "        logits_s = student(xb)\n"
    "        loss = distill_loss(logits_s, logits_t, yb)\n"
    "        opt.zero_grad(); loss.backward(); opt.step()\n"
    "print(f'Student | accuracy {evaluate(student):.4f} | size {model_size_mb(student):.2f} MB')\n"
))

cells.append(md("## 6. Putting it together - a comparison plot"))
cells.append(code(
    "rows = [\n"
    "    ('baseline', evaluate(baseline), model_size_mb(baseline), latency(baseline)),\n"
    "    ('pruned 50% + fine-tune', evaluate(pruned), model_size_mb(pruned), latency(pruned)),\n"
    "    ('dynamic INT8', evaluate(quant_dynamic), model_size_mb(quant_dynamic), latency(quant_dynamic)),\n"
    "    ('QAT INT8', evaluate(qat_quant), model_size_mb(qat_quant), latency(qat_quant)),\n"
    "    ('distilled student', evaluate(student), model_size_mb(student), latency(student)),\n"
    "]\n"
    "header = ('Model', 'Acc', 'MB', 'Lat(ms)')\n"
    "print(f'{header[0]:30s} {header[1]:>6s} {header[2]:>6s} {header[3]:>10s}')\n"
    "for r in rows:\n"
    "    print(f'{r[0]:30s} {r[1]:6.4f} {r[2]:6.2f} {r[3]:10.2f}')\n"
    "\n"
    "labels = [r[0] for r in rows]\n"
    "accs   = [r[1] for r in rows]\n"
    "sizes  = [r[2] for r in rows]\n"
    "fig, ax = plt.subplots(figsize=(7, 4))\n"
    "ax.scatter(sizes, accs, s=80)\n"
    "for x, y, lab in zip(sizes, accs, labels):\n"
    "    ax.annotate(lab, (x, y), fontsize=8, xytext=(5, 5), textcoords='offset points')\n"
    "ax.set_xlabel('Size on disk (MB)'); ax.set_ylabel('Test accuracy')\n"
    "ax.set_title('Accuracy vs size after each compression technique')\n"
    "ax.grid(alpha=0.3); fig.tight_layout(); fig.savefig(IMG_DIR / '01_size_vs_acc.png', dpi=150); plt.show()\n"
))

cells.append(md("## 7. Exercise solutions\n"
                "\n"
                "### 7.1 MCQ answer key\n"
                "\n"
                "| Q | Answer | Why |\n"
                "|---|--------|-----|\n"
                "| 1 | (b) Post-training INT8 quantization | One line of code, ~4x size reduction, typically <1 pp accuracy loss. |\n"
                "| 2 | (b) Hardware cannot exploit unstructured sparsity | Standard kernels iterate every element regardless of zeros. |\n"
                "| 3 | (b) Aligns the int8 range with the asymmetric float range | Zero-point shifts the int8 grid. |\n"
                "| 4 | (a) PTQ uses calibration data only, QAT trains with fake-quant | QAT recovers PTQ accuracy losses. |\n"
                "| 5 | (b) Sub-network with original initialisation can be trained to match the full one | Lottery Ticket Hypothesis. |\n"
                "| 6 | (b) Spreads softmax mass so the student learns relative rankings | Temperature softens the target. |\n"
                "| 7 | (b) Depthwise 3x3 conv + 1x1 pointwise conv | Standard MobileNet trick. |\n"
                "| 8 | (b) SmoothQuant / GPTQ-style activation-aware quantization | Designed for transformer activation outliers. |\n"
                "| 9 | (b) GPU kernels run asynchronously | Sync forces the host to wait. |\n"
                "| 10 | (b) Speculative decoding / KV caching | Both yield 2-3x LLM speed-ups. |\n"
                "| 11 | (b) cuSPARSELt has native kernels for 2:4 sparsity | Generic unstructured sparsity has no hardware support. |\n"))

cells.append(md("### 7.2 ResNet-152 -> Android 50 ms pipeline\n"
                "Stage 1 - **knowledge distillation** to a MobileNetV3-Large student: from 60M parameters to ~5M, "
                "accuracy gap typically 1-3 pp.\n"
                "Stage 2 - **structured pruning** of the residual blocks: trim 30-40 percent of channels with "
                "iterative pruning + fine-tune.\n"
                "Stage 3 - **INT8 quantization-aware training** with the Android NNAPI as target: 4x size reduction, "
                "another 2-4x speed-up on hardware with INT8 SIMD.\n"
                "Stage 4 - **ONNX export + TFLite or PyTorch Mobile** with delegate to the NNAPI / GPU delegate. "
                "Profile on the actual device.\n"
                "\n"
                "If still over budget: try a smaller input resolution (224 -> 192 -> 160), then a smaller backbone "
                "(MobileNetV3-Small). At this point a **smaller architecture** is cheaper than further compression."))

cells.append(md("### 7.3 Unstructured vs structured pruning\n"
                "**Unstructured** pruning sets individual weights to zero. A modern overparameterised model can lose 95 percent "
                "of its weights with almost no accuracy drop because the remaining 5 percent forms a Lottery-Ticket-style "
                "subnetwork that fits the data. The downside: GEMM kernels still iterate over the zeros, so no real speed-up.\n"
                "\n"
                "**Structured** pruning removes whole rows, columns, channels or attention heads. The remaining computation "
                "is dense and the speed-up is real, but the same percentage of weights removed corresponds to a much larger "
                "loss of capacity because you cannot pick which entries inside each unit are most informative.\n"
                "\n"
                "Implications:\n"
                "- (a) **CPU deployment**: prefer structured pruning - the only way to translate sparsity into latency wins.\n"
                "- (b) **A100 GPU with cuSPARSELt**: use 2:4 fine-grained structured sparsity, which gets ~1.5x speed-up at "
                "  50 percent sparsity with no accuracy loss."))

cells.append(md("### 7.4 GPTQ vs AWQ\n"
                "**GPTQ** approximates layer-wise weight quantization by minimising the reconstruction error of the layer "
                "output, using a small calibration set (~128 samples).\n"
                "**AWQ** identifies which channels carry large activations and *scales* them before quantization so they fit "
                "into the int4 grid without losing information; the channels are then rescaled at inference.\n"
                "Calibration: GPTQ needs labeled examples in the model's typical distribution; AWQ needs only activation "
                "statistics.\n"
                "For a code-completion model fine-tuned on a proprietary codebase, **AWQ** is the safer choice because it "
                "preserves the salient outlier activations that contain the codebase-specific style; GPTQ on a "
                "general-language calibration set would over-prioritise generic-text channels."))

cells.append(md("### 7.5 Why PTQ failed on a transformer\n"
                "Transformer activations have heavy-tailed outliers in a small number of channels (often the residual-stream "
                "channels). A symmetric int8 quantization grid wastes most of its dynamic range on a few outliers and rounds "
                "the rest of the channels into the same bin, losing precision where the real signal lives.\n"
                "QAT recovers accuracy by letting the model learn weights that produce smaller outliers. The targeted "
                "alternative is **SmoothQuant** (and **AWQ** above), which shifts the difficulty of quantization from "
                "activations to weights using a calibration-derived scale, without retraining."))

cells.append(md("### 7.6 18 ms CPU vs 9 ms NPU - three technical reasons + one ops reason\n"
                "1. **Dedicated INT8 SIMD** in the NPU vs vectorised CPU: an NPU has 4-8x more multiplier-adders per cycle.\n"
                "2. **Reduced memory traffic**: NPU operates on tile-sized buffers in on-chip SRAM, avoiding DRAM round-trips.\n"
                "3. **Fused operators**: NPU drivers fuse Conv + BatchNorm + ReLU into a single hardware kernel, eliminating intermediate writes.\n"
                "\n"
                "**Operational reason for rejection**: NPU drivers and SDKs are vendor-specific (Qualcomm Hexagon, Apple Neural Engine, Samsung NPU). Shipping an NPU-optimised model means a custom build per device family, much higher QA cost and longer release cycles. If a single CPU build is fast enough, ship that instead."))

cells.append(md("### 7.7 Two-engineer-week compression budget\n"
                "Starting model: 280 MB, 410 ms. Target: 40 MB, 60 ms.\n"
                "\n"
                "**Decision tree:**\n"
                "1. **Distill** to a 3x smaller architecture. Stop if: distillation lands below 80 percent of the teacher's accuracy.\n"
                "2. **Static INT8 quantization** with QAT to recover accuracy. Stop if: latency target hit and accuracy delta acceptable.\n"
                "3. **Structured channel pruning** at 30-50 percent ratio with iterative fine-tune. Stop if: latency drops below 1.5x target.\n"
                "4. **Operator fusion** + smaller input resolution. Stop if: any of the above leaves you within 20 percent of target.\n"
                "5. **Abandon further compression** and ship horizontal scaling once: (a) distilled-quantized-pruned still > 80 MB or > 100 ms, AND (b) further compression is below 0.5 pp accuracy per week of work. At that point a 2-replica deployment is cheaper than another month of engineering."))

cells.append(md("---\n*End of Chapter 9.*\n"))

build_notebook(cells, OUT, kernel_name='python3', display_name='Python 3 (Deep Learning)')
print('Built', OUT)
