"""Build Chapter 1 notebook: Neural Network Foundations using Python and NumPy."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from _nbutils import build_notebook, md, code

CHAPTER = 1
OUT = pathlib.Path(__file__).parent / f"Chapter_{CHAPTER}" / f"Chapter_{CHAPTER}_Neural_Network_Foundations.ipynb"

cells = []

cells.append(md(
    "# Chapter 1: Neural Network Foundations Using Python and NumPy\n"
    "\n"
    "*Deep Learning Crash Course - BPB Publications*\n"
    "\n"
    "This notebook contains the complete, executable code for Chapter 1, "
    "covering perceptrons, activation functions, forward propagation, loss functions, "
    "backpropagation, optimisers and a final from-scratch neural network — concluded with "
    "solutions to the chapter exercises.\n"
    "\n"
    "**Sections**\n"
    "1. Setup and helpers\n"
    "2. Perceptron implementation\n"
    "3. Activation functions\n"
    "4. Forward propagation through multiple layers\n"
    "5. Loss functions\n"
    "6. Backpropagation and training the XOR problem\n"
    "7. Optimisers (SGD, Momentum, RMSprop, Adam)\n"
    "8. Complete neural network on a real dataset\n"
    "9. TensorFlow/Keras equivalent\n"
    "10. Exercise solutions\n"
))

cells.append(md("## 1. Setup and helpers"))
cells.append(code(
    "import os\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "from pathlib import Path\n"
    "\n"
    "IMG_DIR = Path('images')\n"
    "IMG_DIR.mkdir(exist_ok=True)\n"
    "\n"
    "def save_fig(name, fig=None, dpi=150):\n"
    "    \"\"\"Save the current (or given) figure as PNG into the chapter images folder.\"\"\"\n"
    "    fig = fig or plt.gcf()\n"
    "    path = IMG_DIR / f'{name}.png'\n"
    "    fig.savefig(path, dpi=dpi, bbox_inches='tight')\n"
    "    print(f'Saved {path}')\n"
    "\n"
    "RNG = np.random.default_rng(seed=42)\n"
    "print('NumPy version:', np.__version__)\n"
))

cells.append(md("## 2. Perceptron implementation\n"
                "\n"
                "Rosenblatt's perceptron learns a linear decision boundary by adjusting weights "
                "whenever it misclassifies a training example."))
cells.append(code(
    "class Perceptron:\n"
    "    def __init__(self, n_features, lr=0.1, epochs=20):\n"
    "        self.w = np.zeros(n_features)\n"
    "        self.b = 0.0\n"
    "        self.lr = lr\n"
    "        self.epochs = epochs\n"
    "        self.history = []\n"
    "\n"
    "    def predict(self, X):\n"
    "        return np.where(X @ self.w + self.b >= 0.0, 1, 0)\n"
    "\n"
    "    def fit(self, X, y):\n"
    "        for epoch in range(self.epochs):\n"
    "            errors = 0\n"
    "            for xi, target in zip(X, y):\n"
    "                update = self.lr * (target - self.predict(xi.reshape(1, -1))[0])\n"
    "                self.w += update * xi\n"
    "                self.b += update\n"
    "                errors += int(update != 0.0)\n"
    "            self.history.append(errors)\n"
    "            if errors == 0:\n"
    "                break\n"
    "        return self\n"
    "\n"
    "# Linearly separable AND-gate-like data\n"
    "X_lin = np.array([[2, 3], [1, 1], [2, 1], [3, 2], [6, 5], [7, 7], [8, 6], [7, 8]])\n"
    "y_lin = np.array([0, 0, 0, 0, 1, 1, 1, 1])\n"
    "\n"
    "p = Perceptron(n_features=2, lr=0.1, epochs=20).fit(X_lin, y_lin)\n"
    "print('Training errors per epoch:', p.history)\n"
    "print('Final accuracy:', (p.predict(X_lin) == y_lin).mean())\n"
))
cells.append(code(
    "# Decision boundary visualisation\n"
    "xx, yy = np.meshgrid(np.linspace(0, 9, 200), np.linspace(0, 9, 200))\n"
    "grid = np.c_[xx.ravel(), yy.ravel()]\n"
    "preds = p.predict(grid).reshape(xx.shape)\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(6, 5))\n"
    "ax.contourf(xx, yy, preds, alpha=0.25, cmap='coolwarm')\n"
    "ax.scatter(*X_lin.T, c=y_lin, cmap='coolwarm', edgecolor='k', s=80)\n"
    "ax.set_title('Perceptron decision boundary')\n"
    "ax.set_xlabel('x1'); ax.set_ylabel('x2')\n"
    "save_fig('01_perceptron_boundary')\n"
    "plt.show()\n"
))
cells.append(code(
    "# Demonstrating that a single perceptron cannot solve XOR\n"
    "X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=float)\n"
    "y_xor = np.array([0, 1, 1, 0])\n"
    "p_xor = Perceptron(n_features=2, lr=0.1, epochs=200).fit(X_xor, y_xor)\n"
    "acc = (p_xor.predict(X_xor) == y_xor).mean()\n"
    "print(f'XOR accuracy with a single perceptron: {acc:.2f} (cannot exceed 0.75)')\n"
))

cells.append(md("## 3. Activation functions\n"
                "\n"
                "Activation functions give a network its non-linearity. We visualise each function "
                "and its derivative side-by-side."))
cells.append(code(
    "def sigmoid(x):        return 1.0 / (1.0 + np.exp(-x))\n"
    "def sigmoid_deriv(x):  s = sigmoid(x); return s * (1 - s)\n"
    "def tanh(x):           return np.tanh(x)\n"
    "def tanh_deriv(x):     return 1 - np.tanh(x) ** 2\n"
    "def relu(x):           return np.maximum(0.0, x)\n"
    "def relu_deriv(x):     return (x > 0).astype(float)\n"
    "def leaky_relu(x, a=0.01): return np.where(x > 0, x, a * x)\n"
    "def leaky_relu_deriv(x, a=0.01): return np.where(x > 0, 1.0, a)\n"
    "def softmax(z):\n"
    "    e = np.exp(z - z.max(axis=-1, keepdims=True))\n"
    "    return e / e.sum(axis=-1, keepdims=True)\n"
    "\n"
    "x = np.linspace(-5, 5, 400)\n"
    "fig, axes = plt.subplots(2, 2, figsize=(10, 7))\n"
    "for ax, (name, f, fd) in zip(axes.flat, [\n"
    "    ('Sigmoid', sigmoid, sigmoid_deriv),\n"
    "    ('Tanh', tanh, tanh_deriv),\n"
    "    ('ReLU', relu, relu_deriv),\n"
    "    ('Leaky ReLU', leaky_relu, leaky_relu_deriv),\n"
    "]):\n"
    "    ax.plot(x, f(x), label=name)\n"
    "    ax.plot(x, fd(x), '--', label=f'{name}\\u2032')\n"
    "    ax.axhline(0, color='gray', lw=0.5); ax.axvline(0, color='gray', lw=0.5)\n"
    "    ax.set_title(name); ax.legend(); ax.grid(alpha=0.3)\n"
    "plt.tight_layout(); save_fig('02_activations'); plt.show()\n"
))

cells.append(md("## 4. Forward propagation through multiple layers\n"
                "\n"
                "A multi-layer perceptron stacks affine transforms and non-linearities. We use He "
                "initialisation for ReLU layers."))
cells.append(code(
    "class MLP:\n"
    "    def __init__(self, layer_sizes, activations, seed=0):\n"
    "        rng = np.random.default_rng(seed)\n"
    "        self.layer_sizes = layer_sizes\n"
    "        self.activations = activations\n"
    "        self.params = {}\n"
    "        for l in range(1, len(layer_sizes)):\n"
    "            fan_in = layer_sizes[l - 1]\n"
    "            scale = np.sqrt(2.0 / fan_in)  # He init for ReLU\n"
    "            self.params[f'W{l}'] = rng.standard_normal((layer_sizes[l - 1], layer_sizes[l])) * scale\n"
    "            self.params[f'b{l}'] = np.zeros((1, layer_sizes[l]))\n"
    "\n"
    "    def _act(self, name, z):\n"
    "        return {'relu': relu, 'sigmoid': sigmoid, 'tanh': tanh,\n"
    "                'softmax': softmax, 'linear': lambda x: x}[name](z)\n"
    "\n"
    "    def forward(self, X):\n"
    "        cache = {'A0': X}\n"
    "        A = X\n"
    "        for l in range(1, len(self.layer_sizes)):\n"
    "            Z = A @ self.params[f'W{l}'] + self.params[f'b{l}']\n"
    "            A = self._act(self.activations[l - 1], Z)\n"
    "            cache[f'Z{l}'] = Z; cache[f'A{l}'] = A\n"
    "        return A, cache\n"
    "\n"
    "net = MLP([4, 8, 3], ['relu', 'softmax'])\n"
    "X_demo = np.random.randn(5, 4)\n"
    "out, _ = net.forward(X_demo)\n"
    "print('Output shape:', out.shape, 'row sums:', out.sum(axis=1))\n"
))

cells.append(md("## 5. Loss functions"))
cells.append(code(
    "def mse(y, y_hat):                return np.mean((y - y_hat) ** 2)\n"
    "def bce(y, y_hat, eps=1e-12):     y_hat = np.clip(y_hat, eps, 1 - eps); return -np.mean(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))\n"
    "def cce(y_onehot, y_hat, eps=1e-12): y_hat = np.clip(y_hat, eps, 1 - eps); return -np.mean(np.sum(y_onehot * np.log(y_hat), axis=1))\n"
    "\n"
    "y_true = np.array([1.0, 0.0, 1.0, 1.0])\n"
    "y_pred = np.array([0.9, 0.1, 0.8, 0.4])\n"
    "print(f'MSE: {mse(y_true, y_pred):.4f}')\n"
    "print(f'Binary CE: {bce(y_true, y_pred):.4f}')\n"
    "\n"
    "y_oh = np.eye(3)[[0, 1, 2, 0]]\n"
    "y_logits = np.random.randn(4, 3)\n"
    "print(f'Categorical CE: {cce(y_oh, softmax(y_logits)):.4f}')\n"
))

cells.append(md("## 6. Backpropagation: training XOR end-to-end\n"
                "\n"
                "We derive gradients via the chain rule for a 2-2-1 network with sigmoid output."))
cells.append(code(
    "def train_xor(epochs=8000, lr=0.5, seed=1):\n"
    "    rng = np.random.default_rng(seed)\n"
    "    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=float)\n"
    "    y = np.array([[0], [1], [1], [0]], dtype=float)\n"
    "    W1 = rng.standard_normal((2, 2)) * 0.5; b1 = np.zeros((1, 2))\n"
    "    W2 = rng.standard_normal((2, 1)) * 0.5; b2 = np.zeros((1, 1))\n"
    "    losses = []\n"
    "    for ep in range(epochs):\n"
    "        Z1 = X @ W1 + b1; A1 = np.tanh(Z1)\n"
    "        Z2 = A1 @ W2 + b2; A2 = sigmoid(Z2)\n"
    "        loss = bce(y, A2)\n"
    "        losses.append(loss)\n"
    "        # Backprop\n"
    "        dZ2 = (A2 - y)\n"
    "        dW2 = A1.T @ dZ2 / len(X); db2 = dZ2.mean(axis=0, keepdims=True)\n"
    "        dA1 = dZ2 @ W2.T\n"
    "        dZ1 = dA1 * (1 - np.tanh(Z1) ** 2)\n"
    "        dW1 = X.T @ dZ1 / len(X); db1 = dZ1.mean(axis=0, keepdims=True)\n"
    "        W1 -= lr * dW1; b1 -= lr * db1; W2 -= lr * dW2; b2 -= lr * db2\n"
    "    preds = (sigmoid(np.tanh(X @ W1 + b1) @ W2 + b2) > 0.5).astype(int)\n"
    "    return losses, preds, y.astype(int)\n"
    "\n"
    "losses, preds, y_xor_int = train_xor()\n"
    "print('Predictions:', preds.ravel(), 'Truth:', y_xor_int.ravel())\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(6, 4))\n"
    "ax.plot(losses); ax.set_xlabel('Epoch'); ax.set_ylabel('Loss')\n"
    "ax.set_title('XOR training loss with a 2-2-1 MLP')\n"
    "ax.grid(alpha=0.3); save_fig('03_xor_loss'); plt.show()\n"
))

cells.append(md("## 7. Optimisers: SGD vs Momentum vs RMSprop vs Adam\n"
                "\n"
                "We minimise a noisy quadratic to visualise convergence speed."))
cells.append(code(
    "def f(w):   return 0.5 * (w[0] ** 2 + 10 * w[1] ** 2)\n"
    "def grad(w): return np.array([w[0], 10 * w[1]])\n"
    "\n"
    "def optimise(name, steps=80, lr=0.1, beta1=0.9, beta2=0.999, eps=1e-8):\n"
    "    w = np.array([5.0, 1.0])\n"
    "    m = np.zeros_like(w); v = np.zeros_like(w)\n"
    "    path = [w.copy()]\n"
    "    for t in range(1, steps + 1):\n"
    "        g = grad(w)\n"
    "        if name == 'sgd':\n"
    "            w -= lr * g\n"
    "        elif name == 'momentum':\n"
    "            m = beta1 * m + g; w -= lr * m\n"
    "        elif name == 'rmsprop':\n"
    "            v = beta2 * v + (1 - beta2) * g ** 2; w -= lr * g / (np.sqrt(v) + eps)\n"
    "        elif name == 'adam':\n"
    "            m = beta1 * m + (1 - beta1) * g\n"
    "            v = beta2 * v + (1 - beta2) * g ** 2\n"
    "            m_hat = m / (1 - beta1 ** t); v_hat = v / (1 - beta2 ** t)\n"
    "            w -= lr * m_hat / (np.sqrt(v_hat) + eps)\n"
    "        path.append(w.copy())\n"
    "    return np.array(path)\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(7, 5))\n"
    "for name in ['sgd', 'momentum', 'rmsprop', 'adam']:\n"
    "    path = optimise(name)\n"
    "    ax.plot([f(w) for w in path], label=name)\n"
    "ax.set_xlabel('Step'); ax.set_ylabel('f(w)'); ax.set_yscale('log')\n"
    "ax.set_title('Optimiser convergence on a poorly-conditioned quadratic')\n"
    "ax.legend(); ax.grid(alpha=0.3)\n"
    "save_fig('04_optimisers'); plt.show()\n"
))

cells.append(md("## 8. Complete neural network on the moons dataset\n"
                "\n"
                "Putting everything together to train an end-to-end binary classifier."))
cells.append(code(
    "from sklearn.datasets import make_moons\n"
    "from sklearn.model_selection import train_test_split\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "\n"
    "X, y = make_moons(n_samples=1000, noise=0.2, random_state=42)\n"
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n"
    "scaler = StandardScaler().fit(X_train)\n"
    "X_train_s, X_test_s = scaler.transform(X_train), scaler.transform(X_test)\n"
    "y_train_oh = np.eye(2)[y_train]\n"
    "y_test_oh = np.eye(2)[y_test]\n"
    "\n"
    "class NeuralNet:\n"
    "    def __init__(self, sizes, lr=0.05, seed=0):\n"
    "        rng = np.random.default_rng(seed)\n"
    "        self.params = {}\n"
    "        for l in range(1, len(sizes)):\n"
    "            self.params[f'W{l}'] = rng.standard_normal((sizes[l-1], sizes[l])) * np.sqrt(2 / sizes[l-1])\n"
    "            self.params[f'b{l}'] = np.zeros((1, sizes[l]))\n"
    "        self.sizes = sizes; self.lr = lr\n"
    "        self.m = {k: np.zeros_like(v) for k, v in self.params.items()}\n"
    "        self.v = {k: np.zeros_like(v) for k, v in self.params.items()}\n"
    "        self.t = 0\n"
    "\n"
    "    def forward(self, X):\n"
    "        cache = {'A0': X}; A = X\n"
    "        for l in range(1, len(self.sizes) - 1):\n"
    "            Z = A @ self.params[f'W{l}'] + self.params[f'b{l}']\n"
    "            A = np.maximum(0, Z)\n"
    "            cache[f'Z{l}'] = Z; cache[f'A{l}'] = A\n"
    "        L = len(self.sizes) - 1\n"
    "        Z = A @ self.params[f'W{L}'] + self.params[f'b{L}']\n"
    "        cache[f'Z{L}'] = Z; cache[f'A{L}'] = softmax(Z)\n"
    "        return cache[f'A{L}'], cache\n"
    "\n"
    "    def backward(self, cache, y):\n"
    "        grads = {}; L = len(self.sizes) - 1\n"
    "        m = y.shape[0]\n"
    "        dZ = cache[f'A{L}'] - y\n"
    "        for l in range(L, 0, -1):\n"
    "            grads[f'W{l}'] = cache[f'A{l-1}'].T @ dZ / m\n"
    "            grads[f'b{l}'] = dZ.mean(axis=0, keepdims=True)\n"
    "            if l > 1:\n"
    "                dA = dZ @ self.params[f'W{l}'].T\n"
    "                dZ = dA * (cache[f'Z{l-1}'] > 0)\n"
    "        return grads\n"
    "\n"
    "    def step_adam(self, grads, beta1=0.9, beta2=0.999, eps=1e-8):\n"
    "        self.t += 1\n"
    "        for k in grads:\n"
    "            self.m[k] = beta1 * self.m[k] + (1 - beta1) * grads[k]\n"
    "            self.v[k] = beta2 * self.v[k] + (1 - beta2) * grads[k] ** 2\n"
    "            m_hat = self.m[k] / (1 - beta1 ** self.t)\n"
    "            v_hat = self.v[k] / (1 - beta2 ** self.t)\n"
    "            self.params[k] -= self.lr * m_hat / (np.sqrt(v_hat) + eps)\n"
    "\n"
    "    def fit(self, X, y, epochs=80, batch=64, X_val=None, y_val=None):\n"
    "        train_loss, val_loss = [], []\n"
    "        for ep in range(epochs):\n"
    "            idx = np.random.permutation(len(X))\n"
    "            for s in range(0, len(X), batch):\n"
    "                b = idx[s:s + batch]\n"
    "                out, cache = self.forward(X[b])\n"
    "                grads = self.backward(cache, y[b])\n"
    "                self.step_adam(grads)\n"
    "            out, _ = self.forward(X); train_loss.append(cce(y, out))\n"
    "            if X_val is not None:\n"
    "                vout, _ = self.forward(X_val); val_loss.append(cce(y_val, vout))\n"
    "        return train_loss, val_loss\n"
    "\n"
    "    def predict(self, X):\n"
    "        out, _ = self.forward(X)\n"
    "        return out.argmax(axis=1)\n"
    "\n"
    "net = NeuralNet([2, 16, 16, 2], lr=0.01)\n"
    "tr, va = net.fit(X_train_s, y_train_oh, epochs=80, batch=64,\n"
    "                 X_val=X_test_s, y_val=y_test_oh)\n"
    "acc = (net.predict(X_test_s) == y_test).mean()\n"
    "print(f'Test accuracy: {acc:.3f}')\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(7, 4))\n"
    "ax.plot(tr, label='train'); ax.plot(va, label='val')\n"
    "ax.set_xlabel('Epoch'); ax.set_ylabel('Cross-entropy')\n"
    "ax.set_title('From-scratch network on moons'); ax.legend(); ax.grid(alpha=0.3)\n"
    "save_fig('05_moons_curves'); plt.show()\n"
))

cells.append(md("## 9. TensorFlow / Keras equivalent\n"
                "\n"
                "The same model in Keras takes a few lines. We keep the import optional so the "
                "rest of the notebook still runs without TensorFlow installed."))
cells.append(code(
    "# If your machine has an NVIDIA GPU but is missing the CUDA toolkit (`ptxas`),\n"
    "# TensorFlow's XLA JIT compiler will crash the kernel. The from-scratch NumPy code\n"
    "# above does not need a GPU, so we hide it from TensorFlow for this cell.\n"
    "# Remove the next two lines once your CUDA install is complete.\n"
    "import os\n"
    "os.environ.setdefault('CUDA_VISIBLE_DEVICES', '-1')\n"
    "os.environ.setdefault('TF_CPP_MIN_LOG_LEVEL', '2')\n"
    "\n"
    "try:\n"
    "    import tensorflow as tf\n"
    "    tf.random.set_seed(42)\n"
    "    keras_model = tf.keras.Sequential([\n"
    "        tf.keras.layers.Input(shape=(2,)),\n"
    "        tf.keras.layers.Dense(16, activation='relu'),\n"
    "        tf.keras.layers.Dense(16, activation='relu'),\n"
    "        tf.keras.layers.Dense(2, activation='softmax'),\n"
    "    ])\n"
    "    keras_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n"
    "    hist = keras_model.fit(X_train_s, y_train_oh, validation_data=(X_test_s, y_test_oh),\n"
    "                           epochs=40, batch_size=64, verbose=0)\n"
    "    print('Final val accuracy:', hist.history['val_accuracy'][-1])\n"
    "except ModuleNotFoundError:\n"
    "    print('TensorFlow not installed - skipping Keras section.')\n"
))

cells.append(md("## 10. Exercise solutions\n"
                "\n"
                "### 10.1 Multiple-choice answers (with brief justifications)\n"
                "\n"
                "| Q | Answer | Why |\n"
                "|---|--------|-----|\n"
                "| 1 | (b) Synaptic strength | A weight scales the input signal, mirroring synaptic strength. |\n"
                "| 2 | (c) Cannot solve non-linearly separable problems | A single linear boundary cannot represent XOR. |\n"
                "| 3 | (d) ReLU | Standard default for deep hidden layers; cheap and avoids saturation for positive inputs. |\n"
                "| 4 | (b) Dying ReLU | Leaky ReLU keeps a small negative slope so neurons can recover. |\n"
                "| 5 | (b) Stable gradients and faster convergence | Scaling avoids dominant features and vanishing/exploding gradients. |\n"
                "| 6 | (c) Categorical cross-entropy | The natural loss for multi-class probability outputs. |\n"
                "| 7 | (c) Chain rule | Each layer's gradient is the product of its local derivative with the upstream gradient. |\n"
                "| 8 | (b) Counteract the early-iteration bias of the moving averages | Without correction, m and v are heavily biased toward zero. |\n"
                "| 9 | (c) Dropout | Random deactivation forces redundancy and reduces over-fitting. |\n"
                "| 10 | (b) Automatic differentiation (autograd) | Frameworks build a computational graph and differentiate it for you. |\n"
                ))

cells.append(md("### 10.2 Why a stack of linear layers is still linear\n"
                "If every layer is $f_l(x) = W_l x + b_l$, then composing two linear layers gives\n"
                "$f_2(f_1(x)) = W_2 (W_1 x + b_1) + b_2 = (W_2 W_1) x + (W_2 b_1 + b_2)$, which is "
                "another affine map with weights $W_2 W_1$ and bias $W_2 b_1 + b_2$. Adding more "
                "linear layers only changes those constants. Non-linear activations are what allow "
                "the network to represent non-linear functions."))
cells.append(code(
    "rng = np.random.default_rng(0)\n"
    "W1, b1 = rng.standard_normal((4, 8)), rng.standard_normal((1, 8))\n"
    "W2, b2 = rng.standard_normal((8, 3)), rng.standard_normal((1, 3))\n"
    "W3, b3 = rng.standard_normal((3, 2)), rng.standard_normal((1, 2))\n"
    "X = rng.standard_normal((5, 4))\n"
    "stacked = ((X @ W1 + b1) @ W2 + b2) @ W3 + b3\n"
    "W_eff = W1 @ W2 @ W3; b_eff = (b1 @ W2 + b2) @ W3 + b3\n"
    "single = X @ W_eff + b_eff\n"
    "print('Max absolute difference:', np.max(np.abs(stacked - single)))\n"
))

cells.append(md("### 10.3 Vanishing gradient problem and susceptible activations\n"
                "Vanishing gradients occur when the product of layer Jacobians shrinks "
                "exponentially with depth. Sigmoid saturates outside roughly $[-4, 4]$ with derivative "
                "$\\le 0.25$, so each layer multiplies the gradient by a factor below one. Tanh has the "
                "same problem but with a max derivative of 1.0 — better than sigmoid but still prone "
                "to saturation. ReLU's derivative is 0 or 1, so it suffers less, but very negative "
                "pre-activations create the 'dying ReLU' problem."))
cells.append(code(
    "x = np.linspace(-8, 8, 400)\n"
    "fig, ax = plt.subplots(figsize=(7, 4))\n"
    "ax.plot(x, sigmoid_deriv(x), label=\"sigmoid'\")\n"
    "ax.plot(x, tanh_deriv(x), label=\"tanh'\")\n"
    "ax.plot(x, relu_deriv(x), label=\"relu'\")\n"
    "ax.set_xlabel('pre-activation'); ax.set_ylabel('derivative')\n"
    "ax.set_title('Activation derivatives - regions of saturation')\n"
    "ax.legend(); ax.grid(alpha=0.3); save_fig('06_derivatives'); plt.show()\n"
))

cells.append(md("### 10.4 Two-layer backprop derivation (ReLU hidden, sigmoid output)\n"
                "Forward pass:\n"
                "$z_1 = W_1 x + b_1, \\; a_1 = \\max(0, z_1), \\; z_2 = W_2 a_1 + b_2, \\; \\hat{y} = \\sigma(z_2)$.\n"
                "\n"
                "With binary cross-entropy loss $L = -y \\log \\hat{y} - (1-y) \\log(1-\\hat{y})$:\n"
                "\n"
                "- $\\partial L / \\partial z_2 = \\hat{y} - y$\n"
                "- $\\partial L / \\partial W_2 = a_1^T (\\hat{y} - y)$\n"
                "- $\\partial L / \\partial b_2 = \\hat{y} - y$\n"
                "- $\\partial L / \\partial a_1 = (\\hat{y} - y) W_2^T$\n"
                "- $\\partial L / \\partial z_1 = \\partial L / \\partial a_1 \\odot \\mathbf{1}[z_1 > 0]$\n"
                "- $\\partial L / \\partial W_1 = x^T (\\partial L / \\partial z_1)$, $\\partial L / \\partial b_1 = \\partial L / \\partial z_1$\n"))

cells.append(md("### 10.5 Batch vs SGD vs mini-batch\n"
                "**Batch gradient descent** uses the whole training set per update. Updates are "
                "low-variance and the path is smooth but slow on large datasets; one epoch = one "
                "update.\n"
                "\n"
                "**SGD** updates on a single example. Very noisy, can escape shallow minima, but "
                "convergence is jittery and the final loss often oscillates.\n"
                "\n"
                "**Mini-batch GD** sits between the two: 32-512 examples per update. It exploits "
                "vectorised hardware and gives a useful trade-off between variance and throughput. "
                "This is what is used in practice."))

cells.append(md("### 10.6 How Adam adapts the learning rate per parameter\n"
                "Adam maintains two exponential moving averages per parameter — $m_t$ for the "
                "gradient and $v_t$ for its square. The effective learning rate becomes "
                "$\\eta \\hat{m}_t / (\\sqrt{\\hat{v}_t} + \\epsilon)$, so parameters with consistently "
                "large gradients get a smaller effective step than those with small or noisy "
                "gradients. Compared to a fixed learning rate this rescales each dimension on the "
                "fly, which is particularly helpful when parameter magnitudes differ by orders of "
                "magnitude (e.g. embedding tables vs final-layer biases)."))
cells.append(code(
    "# Visualise Adam vs SGD step magnitudes on the noisy quadratic above\n"
    "sgd_path = optimise('sgd'); adam_path = optimise('adam')\n"
    "fig, ax = plt.subplots(figsize=(6, 4))\n"
    "ax.plot(np.linalg.norm(np.diff(sgd_path, axis=0), axis=1), label='SGD step size')\n"
    "ax.plot(np.linalg.norm(np.diff(adam_path, axis=0), axis=1), label='Adam step size')\n"
    "ax.set_xlabel('Step'); ax.set_ylabel('|step|'); ax.legend(); ax.grid(alpha=0.3)\n"
    "ax.set_title('Per-step update magnitude'); save_fig('07_adam_step'); plt.show()\n"
))

cells.append(md("---\n"
                "*End of Chapter 1 — all figures are saved into `images/` for the book bundle.*\n"))

build_notebook(cells, OUT, kernel_name='python3', display_name='Python 3 (Deep Learning)')
print('Built', OUT)
